### ISSUE TITLE
Remove base and root from config

### ISSUE THREAD

**Issue by dionyziz** [dionyziz/endofcodes#141]
These can be automatically detected so they don't need to be in the config. Figure out a way to detect them and remove them from the config.

**Comment by vitsalis** [comment]
do you have any idea how?

**Comment by dionyziz** [comment]
Use `getcwd()` like we discussed about `root`. `base` can be inferred by looking at the request URI, parsing it, and deducing the base.

**Comment by bugos** [comment]
Maybe this is what you mean?

``` php
$index_file = 'http://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];
$config[ 'base' ] = dirname($index_file); //drop filename and parameters
```

**Comment by vitsalis** [comment]
I don't think `dirname()` will work, because we have some links in the form `endofcodes.com/session/create/`. But thanks for your suggestion! :)

**Comment by dionyziz** [comment]
We know when `session/create` is there though; so we can remove it.

**Comment by bugos** [comment]
What if we use `$_SERVER['SCRIPT_NAME']` instead of  `$_SERVER['REQUEST_URI']`?
