### ISSUE TITLE
Refactor createSelect

### ISSUE THREAD

**Issue by dionyziz** [dionyziz/endofcodes#162]
I'd like to see the following changed in createSelect:
1. Optional arguments are succeeded by mandatory arguments. This is a syntax error and must be fixed.
2. I recommend making the options array a dictionary where dictionary keys correspond to the HTML "value" attribute value and dictionary values correspond to the content.
3. nit: `$option_array` uses underscores, while our style is `camelCase`

**Comment by pkakelas** [comment]
The 1st one is fixed from my previous pull request.
