### ISSUE TITLE
Fix bot update bug

### ISSUE THREAD

**Issue by dionyziz** [dionyziz/endofcodes#168]
The bot is correctly configured appears even if I haven't added a bot.
![screen shot 2014-03-22 at 3 53 19 pm](https://f.cloud.github.com/assets/544572/2490846/65d4719e-b1c9-11e3-90d2-b983585b5850.png)

**Comment by pkakelas** [comment]
@dionyziz I don't see this bug.

**Comment by pkakelas** [comment]
Invalid
