### ISSUE TITLE
config file does not follow DRY between environments

### ISSUE THREAD

**Issue by dionyziz** [dionyziz/endofcodes#249]
The config file currently contains a lot of duplication between the `test` and `development` environments. Suggest that we devise a mechanism to make an environment copy its configuration from another environment and then override particular settings.

**Comment by bugos** [comment]
I suggest we keep the setting that are common to all environments in a `main.php` file. We also have ~~a `local.php` file and~~ `testing.php`, `development.php`, `production.php` files where we keep more specific settings. The `main.php` file should have the lowest priority.

What do you guys think?

**Comment by dionyziz** [comment]
What would `local.php` contain? Would it encompass settings for all three environments?

**Comment by bugos** [comment]
I changed my mind while writting the comment. 
We should drop the `local.php` and keep the local settings in the appropriate `<environment>.php` file.

**Comment by bugos** [comment]
By the way, we should have a security check for the case when the database name for development and testing is the same and warn the user.

**Comment by dionyziz** [comment]
If we have only `<environment>.php`, what is going to be the default deployment configuration?

**Comment by dionyziz** [comment]
Agreed about security check, please make a separate issue.

**Comment by bugos** [comment]
What do you mean? The default settings will be in `main.php`.

**Comment by dionyziz** [comment]
For all 3 environments? The default settings from development differ from testing, for example.

**Comment by bugos** [comment]
What if we add an optional parameter in each config file named e.g. `inherit_from` that can be set equal to the environment from which we copy the settings?

Otherwise we can keep it simple and aggree that all enviroments copy their settings from `development`. What do you think?

**Comment by dionyziz** [comment]
We could make an abstract environment 'base' that is never used directly but all other environments inherit from it. However, it may be advisable to consult how other frameworks such as Django and Rails deal with this. Can you research and see what they do?

**Comment by bugos** [comment]
Rails is using an abstract environment - like the one you suggested - named `defaults`. I guess we can do the same.

**Comment by dionyziz** [comment]
OK
