### ISSUE TITLE
HTTPError pages not loaded correctly due to wrong base.

### ISSUE THREAD

**Issue by bugos** [dionyziz/endofcodes#257]
Depends on #252.
The config is not loaded on HTTPError pages (like 404), so the base is set to "".
The problem occures on pages like `endofcodes.com/invalid/invalid`.

**Comment by bugos** [comment]
I propose that we make the `ControllerBase->getConfig()` function static and we call it from index.php.

**Comment by vitsalis** [comment]
I think we should make an http errors controller. Every controller passes from ControllerBase so we wouldn't have this problem. Also it will be a better API.

**Comment by bugos** [comment]
@VitSalis that's an interesting idea but it would require a lot of refactoring. And I am not sure of how we would call the error controller after we have caught an exception in `index.php`.

I am looking at the code in `ControllerBase` and I think that the function `loadConfig()` does not suit there. Only the last line does load the config. The rest of the code determines the enviroment.

I propose that we make a new function `findEnv()` in `/helpers/config.php/`  and move the enviroment code there. Then we can easily load the config file from `index.php` as I proposed above.

**Comment by vitsalis** [comment]
Everything passes from controllers except from http errors at this point. I think that's wrong.
The ControllerBase gives the basis for a lot of things that are used throughout the whole page.

Also there won't be a lot of refactoring. Just an `http.php` controller, with a `create` method, that takes the HTTP error as a parameter and includes the corresponding view.

**Comment by bugos** [comment]
Ok I agree; I will fix this with a new controller.

@VitSalis thanks for the feedback.
