### ISSUE TITLE
Redirects with go() don't work in CLI.

### ISSUE THREAD

**Issue by bugos** [dionyziz/endofcodes#310]
The `go()` function is defined in `helpers/http.php` and is used to cleanly switch between controllers with an HTTP redirect. 

However this method does not work in CLI.

Additionally it has the disadvantages that: 
1. the original URL is ~~lost~~ changed and 
2. any error parameters have to be passed as GET parameters.

**Comment by dionyziz** [comment]
The second problem you're talking about is a serious problem that makes for quite some duplication in our current controllers - thanks for the catch. How do you recommend we pass error parameters around?

**Comment by dionyziz** [comment]
The original URL is easy to keep in the session - just make the go function store the URL and let the target controller use it at will.

**Comment by dionyziz** [comment]
CLI can be made to utilize go() in two different ways:
1. make the CLI dispatcher catch go requests and dispatch the new request directly without any redirects
2. modify CLI-enabled controllers and have them only use go() for HTTP requests and handle the situation independently for CLI requests as they see fit

I don't see why we can't do both.

**Comment by bugos** [comment]
Why don't we change the controller without reloading the page? We could call `dispatch()` after catching the exception.

**Comment by dionyziz** [comment]
You mean in regular HTTP pages?
